name: sentinel_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rasterio
  - rioxarray
  - xarray
  - geopandas
  - shapely
  - numpy
  - matplotlib
  - pip
  - pip:
      - pystac-client
      - planetary-computer
      - stackstac
      - odc-stac
      - scipy
      - scikit-image
